export const SYSTEM_BOOKMARK_CATEGORY_KEYS = [
  "BUTTOCKS_EXPOSED",
  "FEMALE_BREAST_EXPOSED",
  "FEMALE_GENITALIA_EXPOSED",
  "MALE_BREAST_EXPOSED",
  "ANUS_EXPOSED",
  "FEET_EXPOSED",
  "ARMPITS_EXPOSED",
  "BELLY_EXPOSED",
  "MALE_GENITALIA_EXPOSED",
  "ANUS_COVERED",
  "FEMALE_GENITALIA_COVERED",
] as const;

export type SystemBookmarkCategoryKey =
  (typeof SYSTEM_BOOKMARK_CATEGORY_KEYS)[number];
